BlogTube/BlogTube/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('user.urls')),
    path("group/",include('group.urls')),
    path("blog/",include('blog.urls')),
    path("login/",auth_views.LoginView.as_view(template_name='user/login.html'),name='login'),
    path("logout/",auth_views.LogoutView.as_view(template_name='user/logout.html'),name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BlogTube/blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
    # path("post_create/",views.PostCreateView.as_view(),name='post_create'),
    path("post_create_new/<int:pk>",views.PostCreateViewNew.as_view(),name='post_create_new'),
    # path("group_details/<int:pk>/post_list/",views.PostListView.as_view(),name="post_list"),
    path("post_details/<int:pk>",views.PostDetailView.as_view(),name="post_detail"),
    path("posts_published/",views.PostListView.as_view(),name='post_list'),
    path("post_edit/<int:pk>/<int:gpk>",views.PostUpdateView.as_view(),name="post_edit"),
    path("post_delete/<int:pk>",views.post_delete,name="post_delete"),

]

BlogTube/group/urls.py
from django.urls import path
from . import views

app_name='group'

urlpatterns = [
    path("group_detail/<int:pk>",views.GroupDetailView.as_view(),name='group_detail'),
    path("group_list/",views.GroupListView.as_view(),name='group_list'),
    path("group_create/",views.GroupCreateView.as_view(),name='group_create'),
    path("group_join/<int:pk>",views.GroupJoin.as_view(),name='group_join'),
    path("group_join_invite/<int:pk>", views.GroupJoinInvite.as_view(), name="group_join_invite"),
    path("group_leave/<int:profile_id>/<int:group_id>",views.GroupLeave.as_view(),name='group_leave'),
]

BlogTube/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path("",views.IndexView.as_view(),name='index'),
    path("sign_up/",views.sign_up,name='sign_up'),
    path("profile/<int:pk>",views.ProfileDetailView.as_view(),name='profile'),
]

BlogTube/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from group.models import Group
from django.urls import reverse

# Create your models here.
class Post(models.Model):

    # This user field will not be in form it will be filled with request.user during form validation
    user = models.ForeignKey(User,related_name='posts',on_delete=models.CASCADE)

    group = models.ForeignKey(Group,on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    description = models.TextField()
    created_on = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse("group:group_detail", kwargs={"pk": self.group.pk})
    

    def __str__(self) -> str:
        return self.title

BlogTube/blog/forms.py
from django import forms

class PostForm(forms.ModelForm):

    class Meta():
        fields = ('title','description')

BlogTube/blog/views.py
from django.shortcuts import render,redirect
from .models import Post
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from .forms import PostForm
from django.utils import timezone
from group.models import Group

# Create your views here.

class PostListView(ListView):

    # context_object_name = 'post_list'
    model = Post
    def get_queryset(self):
        return Post.objects.filter(created_on__lte=timezone.now()).order_by('-created_on')
    template_name = 'blog/all_posts.html'
    extra_context = {'title': 'Published Posts'}

class PostCreateViewNew(CreateView):

    model = Post
    fields = ('title','description')

    def form_valid(self, form: PostForm):
        form.instance.user = self.request.user
        group = Group.objects.filter(id=self.kwargs['pk']).first()
        form.instance.group = group
        return super().form_valid(form)
    extra_context = {'title': 'Write Your Blog'}

class PostDetailView(DetailView):

    model = Post
    extra_context = {'title': 'Post'}

class PostUpdateView(UpdateView):
    
    model = Post
    fields = ('title','description')
    # success_url = reverse_lazy('post:post_detail',pk=pk)
    extra_context = {'title': 'Update Your Blog'}


def post_delete(request,pk):
    post = Post.objects.get(id=pk)
    gpk = post.group.id
    post.delete()
    return redirect('group:group_detail',pk=gpk)

BlogTube/blog/templates/blog/all_posts.html
{% extends 'base.html' %}

{% block content %}



<div id="all-post" class="container-fluid">
    <div class="row">
        <div  class="col-lg-8 shadow-sm pt-2 pb-2 mt-3" id="post_list">
        {% for post in post_list %}
        <div id="post-container" >
            <h1><a class="title" href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p id="post-data" class="text-end date">Published On : {{ post.created_on|date:"d-M-Y" }}</p>
            <p id="post-data" class="text-start">Written By : <a id="author" href="{% url 'user:profile' pk=post.user.profile.id %}">{{ post.user}}</a></p>
            <p id="post-data" class="text-start">Published In: <a id="author" href="{% url 'group:group_detail' pk=post.group.pk %}">{{ post.group.name }}</p>            
        </div>
        {% endfor %}
        </div>
    </div>
</div>



{% endblock content %}

BlogTube/blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
	<h1>Do you really want to delete the post {{post.title}}?</h1>
	<form method="POST">
		{% csrf_token %}
		<input type="submit" class="btn btn-warning" value="Delete">
		<a href="{% url 'blog:post_detail' pk=post.pk %}" class="btn btn-secondary">Cancel</a>
		
	</form>	
</div>
{% endblock %}
<!-- action="{% url 'group:group_detail' pk=post.group.pk %}" -->

BlogTube/blog/templates/blog/post_detail.html
{% extends 'base.html' %}


{% block content %}


<div class="container">
    <h1 style="text-align: center;">{{ post.title }}</h1>
    <hr>
    <p style="font-weight: 600;">{{ post.description }}</p>
    <p style="font-weight: bold;" class="text-end"> - {{ post.user}}</p>
    <hr>
    {% if user == post.user %}
    <a class="btn btn-secondary" href="{% url 'blog:post_edit' pk=post.pk gpk=post.group.pk %}">Edit Post</a>
    <a class="btn btn-warning" href="{% url 'blog:post_delete' pk=post.pk %}">Delete</a>
    {% endif %}
</div>

{% endblock content %}

BlogTube/blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container p-3 mt-5" style="border: 1px solid black; border-radius: 10px;">
        <h1 style="text-start: center;">write your blog :</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy}}
            <br>
            <div style="text-align: center;">
                <input type="submit" class="btn btn-success" value="Publish">                
            </div>
        </form>
</div>

{% endblock content %}

BlogTube/blog/templates/blog/post_list.html
{% for post in group.postlist %}

<div class="post-container">
    <a class="post-title" href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a>
    <p id="post-data" class="text-start">Published By - <a id="author" href="{% url 'user:profile' pk=post.user.profile.id %}">{{ post.user}}</a> </p>
    <p id="post-data" class="text-end date">Published On : {{ post.created_on|date:"d-M-Y" }}</p>
    <hr>
</div>
{% endfor %}