BlogTube/BlogTube/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('user.urls')),
    path("group/",include('group.urls')),
    path("blog/",include('blog.urls')),
    path("login/",auth_views.LoginView.as_view(template_name='user/login.html'),name='login'),
    path("logout/",auth_views.LogoutView.as_view(template_name='user/logout.html'),name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BlogTube/blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
    # path("post_create/",views.PostCreateView.as_view(),name='post_create'),
    path("post_create_new/<int:pk>",views.PostCreateViewNew.as_view(),name='post_create_new'),
    # path("group_details/<int:pk>/post_list/",views.PostListView.as_view(),name="post_list"),
    path("post_details/<int:pk>",views.PostDetailView.as_view(),name="post_detail"),
    path("posts_published/",views.PostListView.as_view(),name='post_list'),
    path("post_edit/<int:pk>/<int:gpk>",views.PostUpdateView.as_view(),name="post_edit"),
    path("post_delete/<int:pk>",views.post_delete,name="post_delete"),

]

BlogTube/group/urls.py
from django.urls import path
from . import views

app_name='group'

urlpatterns = [
    path("group_detail/<int:pk>",views.GroupDetailView.as_view(),name='group_detail'),
    path("group_list/",views.GroupListView.as_view(),name='group_list'),
    path("group_create/",views.GroupCreateView.as_view(),name='group_create'),
    path("group_join/<int:pk>",views.GroupJoin.as_view(),name='group_join'),
    path("group_join_invite/<int:pk>", views.GroupJoinInvite.as_view(), name="group_join_invite"),
    path("group_leave/<int:profile_id>/<int:group_id>",views.GroupLeave.as_view(),name='group_leave'),
]

BlogTube/group/models.py
from django.db import models
from user.models import Profile
from django.utils import timezone
# Create your models here.

class Group(models.Model):
    name = models.CharField(max_length=1000)
    description = models.CharField(max_length=5000)

    # This field will be filled through GroupMember.
    profile = models.ManyToManyField(Profile,through='GroupMember')

    @property
    def postlist(self):
        post_list = self.post_set.filter(created_on__lte=timezone.now()).order_by('-created_on')
        return post_list
    
    @property
    def postcount(self):
        posts = self.post_set.all()
        post_count = len([post for post in posts])
        return post_count

    def __str__(self) -> str:
        return self.name

class GroupMember(models.Model):
    profile = models.ForeignKey(Profile,related_name='members',on_delete=models.CASCADE)
    group = models.ForeignKey(Group,related_name='memberships',on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.profile.user.username

    class Meta:
        unique_together = ('profile','group')

BlogTube/group/views.py
from django.shortcuts import render
from .models import Group,GroupMember
from django.urls import reverse_lazy,reverse
from django.http import HttpResponse
from django.contrib import messages

from django.db import IntegrityError

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from django.views.generic import ListView,DetailView,CreateView,RedirectView


# Create your views here.
class GroupListView(ListView):
    
    context_object_name = 'group_list'
    model = Group
    template_name = 'group/group_list.html'
    extra_context = {'title': 'Groups'}

class GroupDetailView(DetailView):

    model = Group
    extra_context = {'title': 'Group Details'}

class GroupCreateView(LoginRequiredMixin,CreateView):
    # login_required = True
    # login_url = "login"
    # redirect_field_name = "group:group_create"
    model = Group
    fields = ('name','description')
    success_url = reverse_lazy('group:group_list')
    extra_context = {'title': 'Create Group'}

class GroupJoin(RedirectView):

    # login_required = True
    # redirect_field_name = 'group/group_detail'
    # pattern_name = 'group:group_detail'
    
    # def get_redirect_url(self, *args **kwargs):
    #     GroupMember.objects.create(profile=self.request.user.username,group=self.group)
    #     return reversed('group:group_detail',kwargs={'pk':self.pk})
        def get_redirect_url(self, *args, **kwargs):
            group = Group.objects.filter(id=self.kwargs['pk']).first()
            GroupMember.objects.create(profile=self.request.user.profile,group=group)
            return reverse("group:group_detail",kwargs={"pk": self.kwargs['pk']})
    
    # def get(self, request, *args,**kwargs):
    #     group = get_object_or_404(Group,id=self.kwargs['pk'])
    #     GroupMember.objects.create(profile=self.request.user.profile,group=group)
    #     return super().get(request, *args, **kwargs)

class GroupJoinInvite(LoginRequiredMixin,RedirectView):

    def get_redirect_url(self, *args, **kwargs):
         return reverse('group:group_detail',kwargs={'pk':self.kwargs['pk']})

class GroupLeave(RedirectView):

    # pattern_name = 'group:group_details'

    # Here i am using profile_id and group_id to select exact GroupMember object for deleting.
    # Came to know about profile_id and group_id from python manage.py shell --> GroupMember.objects.values()

    def get_redirect_url(self, *args, **kwargs):
        Membership_to_delete = GroupMember.objects.get(profile_id=self.kwargs['profile_id'],group_id=self.kwargs['group_id'])
        Membership_to_delete.delete()
        return reverse("group:group_detail",kwargs={"pk": self.kwargs['group_id']})

BlogTube/group/templates/group/group_detail.html
{% extends 'base.html' %}

{% block content %}

<h1><p class="text-center" style="font-size: 50px">{{ group.name }}</p></h1>

<div class="container">
    <hr>
    <div class="row">
        {% if user.profile in group.profile.all %}
            <div class="col-lg-6">
                <a href="{% url 'blog:post_create_new' pk=group.pk %}" class="btn btn-primary">Create your own post</a>
            </div>
            <div class="col-lg-6 text-end">
                <a href="{% url 'group:group_leave' profile_id=user.profile.id group_id=group.id %}" class="btn btn-danger">Leave Group</a>
            </div>
        {% else %}
            {% if user.is_authenticated %}
            <div class="col-lg-6">
                <a href="{% url 'group:group_join' pk=group.pk %}" class="btn btn-success">Join Group</a>
            </div>
            {% else %}
            <div class="col-lg-12">
                <h5><p class="text-end"><a style="text-decoration: none;" href="{% url 'login' %}">Login</a> to join the group and write your own blogs!</p></h5>
            </div>
            {% endif %}
        {% endif %}
    </div>
</div>



<div class="container">
    <hr>
    {% if group.postcount == 0 %}
    <h5><p>Be the first one to publish a post !</p></h5>
    {% else %}
    <h2>Posts published :</h2>
    <hr>
    {% include 'blog/post_list.html' %}
    {% endif %}
</div>

{% endblock content %}

BlogTube/group/templates/group/group_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container p-3 mt-5" style="border: 1px solid black; border-radius: 10px;">
    <form method="POST">
        <h1 style="text-align: center;">Create Group</h1>
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <div style="text-align: center;">
            <input type="submit" class="btn btn-success" value="Create Group">                
        </div>
    </form>
</div>


{% endblock content %}

BlogTube/group/templates/group/group_list.html
{% extends 'base.html' %}

{% block content %}

<div id="all-group" class="container-fluid">
    <div class="container">
      <div class="row">
            <div class="col-lg-4">
                <div class="container mt-3">
                    {% if user.is_authenticated %}
                    <div class="col-lg-8">
                        <h1>Hello {{ user.username }}!</h1>
                    </div> 
                    <div class="col-lg-8">
                        <a class="btn btn-primary" href="{% url 'group:group_create' %}" >Create Group</a>
                    </div>
                    {% else %}
                    <div class="col-lg-8">
                        <h3>Login to create your own group!</h3>
                    </div>
                    <div class="col-lg-8">
                        <a class="btn btn-primary" href="{% url 'group:group_create' %}" >Create Group</a>
                    </div>
                    {% endif %}
                </div>    
            </div>
        
            <div class="col-lg-8">
                {% for group in group_list %}
                <div id="post-container" class="container shadow-sm p-3 mt-3" >
                    <h1><a class="title" style="color: #7a1885;" href="{% url 'group:group_detail' pk=group.pk %}">{{ group.name }}</h1>
                    <p id="post-data">Group Description : {{ group.description }}</p>
                    <p id="post-data" class="text-end">Members : {{ group.memberships.count }}</p>
                    <p id="post-data" class="text-end">Posts : {{ group.postcount }}</p>
                    </a>
                </div>
                
                {% endfor %}
            </div>
        </div>  
    </div>
</div>

{% endblock content %}