BlogTube/BlogTube/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('user.urls')),
    path("group/",include('group.urls')),
    path("blog/",include('blog.urls')),
    path("login/",auth_views.LoginView.as_view(template_name='user/login.html'),name='login'),
    path("logout/",auth_views.LogoutView.as_view(template_name='user/logout.html'),name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BlogTube/blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
    # path("post_create/",views.PostCreateView.as_view(),name='post_create'),
    path("post_create_new/<int:pk>",views.PostCreateViewNew.as_view(),name='post_create_new'),
    # path("group_details/<int:pk>/post_list/",views.PostListView.as_view(),name="post_list"),
    path("post_details/<int:pk>",views.PostDetailView.as_view(),name="post_detail"),
    path("posts_published/",views.PostListView.as_view(),name='post_list'),
    path("post_edit/<int:pk>/<int:gpk>",views.PostUpdateView.as_view(),name="post_edit"),
    path("post_delete/<int:pk>",views.post_delete,name="post_delete"),

]

BlogTube/group/urls.py
from django.urls import path
from . import views

app_name='group'

urlpatterns = [
    path("group_detail/<int:pk>",views.GroupDetailView.as_view(),name='group_detail'),
    path("group_list/",views.GroupListView.as_view(),name='group_list'),
    path("group_create/",views.GroupCreateView.as_view(),name='group_create'),
    path("group_join/<int:pk>",views.GroupJoin.as_view(),name='group_join'),
    path("group_join_invite/<int:pk>", views.GroupJoinInvite.as_view(), name="group_join_invite"),
    path("group_leave/<int:profile_id>/<int:group_id>",views.GroupLeave.as_view(),name='group_leave'),
]

BlogTube/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path("",views.IndexView.as_view(),name='index'),
    path("sign_up/",views.sign_up,name='sign_up'),
    path("profile/<int:pk>",views.ProfileDetailView.as_view(),name='profile'),
]

BlogTube/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      {% if title %}
      BlogTube | {{title}}
      {% else %}
      BlogTube | Insert title
      {% endif %}
    </title>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <!--Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Chivo+Mono:wght@300&family=Dosis&display=swap" rel="stylesheet">

    <!--Logo-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

    <!--Personal CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

</head>
<body>
    <!--Navbar-->
    <nav class="navbar sticky-top navbar-expand-lg" style="background-color: #4158D0;
    background-color: #4158D0;
    background-image: linear-gradient(43deg, #4158D0 8%, #C850C0 83%, #ffae00 100%);" id="navbar">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'user:index' %}">BlogTube</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'user:profile' pk=user.profile.id %}">Welcome {{user.username|title}}</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'user:profile' pk=user.profile.id %}">Profile</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="#">Welcome Guest</a>
              </li>
              {% endif %}
            </ul>
            <ul class="navbar-nav justify-content-end">
                {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'blog:post_list' %}">Posts</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'group:group_list' %}">Groups</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'group:group_create' %}">Create Group</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'blog:post_list' %}">Posts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'group:group_list' %}">Groups</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:sign_up' %}">Sign-up</a>
                </li>
                {% endif %}
            </ul>
          </div>
        </div>
      </nav>

    {% block content %}
    {% endblock content %}
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

</body>
</html>